#Pipeline Name
name: Playwright Tests 
# when does this run
on:
  push:
    branches: [ main ] # after git push run on these branches
  #pull_request:
    #branches: [ main, master ]
jobs: #will run jobs
  playwrighttests:
    #timeout-minutes: 60
    runs-on: ubuntu-latest # run on this OS
    steps: # step list of things you wanna do
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Say hello
        run: echo "Hello, world!"

    
